### ISSUE TITLE
Scope names conflict

### ISSUE THREAD

**Issue by pchaigno** [ashgti/perl-tmbundle#1]
We would like to use this Textmate bundle at github/linguist#900 to highlight Perl 6 code on GitHub.
However, the scope name `source.perl` is already used by Perl 5.

Would you be willing to change the scope name of this grammar to `source.perl6` or something similar?

**Comment by pchaigno** [comment]
@ashgti Any update on this?

**Comment by ashgti** [comment]
I made a new fork of the perl.tmbundle and created a PR for adding perl6 to the perl.tmbundle. 

See https://github.com/textmate/perl.tmbundle/pull/13 so I'll close this and probably also remove this repo since I have a more up to date version of the repo at https://github.com/ashgti/perl.tmbundle
